services:
  postgres:
    build: .
    container_name: postgres-container
    environment:
      POSTGRES_DB: form
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres-data:

networks:
  spring-network: